# Generated by Django 3.1.2 on 2020-10-24 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_auto_20201023_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.PositiveIntegerField()),
                ('protein_goal', models.PositiveIntegerField()),
                ('fat_goal', models.PositiveIntegerField()),
                ('carb_goal', models.PositiveIntegerField()),
                ('calorie_min_max', models.BooleanField()),
                ('set_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='calorie.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
