# Generated by Django 3.1.2 on 2020-10-26 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_auto_20201024_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.PositiveIntegerField()),
                ('protein_goal', models.PositiveIntegerField()),
                ('fat_goal', models.PositiveIntegerField()),
                ('carb_goal', models.PositiveIntegerField()),
                ('calorie_min_max', models.BooleanField()),
                ('set_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_number',
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='calorie.customer'),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='setting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='calorie.customer'),
        ),
    ]
