# Generated by Django 3.1.2 on 2020-10-26 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie', '0004_auto_20201025_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='customer',
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='auth.user'),
            preserve_default=False,
        ),
    ]
