# Generated by Django 3.1.2 on 2020-10-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0006_auto_20201026_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='setting',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='setting',
            name='calorie_min_max',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='carb_goal',
            field=models.PositiveIntegerField(default=130),
        ),
        migrations.AlterField(
            model_name='setting',
            name='fat_goal',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='setting',
            name='protein_goal',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
