# Generated by Django 3.1.2 on 2020-12-04 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0008_auto_20201029_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='fat_perc',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='fat_perc_goal',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='set_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
