# Generated by Django 3.1.2 on 2020-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0009_auto_20201203_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='fat_perc',
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='fat_perc',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
