# Generated by Django 3.1.2 on 2020-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0010_auto_20201203_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyintake',
            name='current_weight',
            field=models.PositiveIntegerField(default=140),
        ),
        migrations.AddField(
            model_name='setting',
            name='weight_goal',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
